Add optional multiline support.
QEDK/configparser-rs pull request #28
Opened 2022-03-16 15:26 UTC by jgrund

This patch adds optional multiline support with the `Ini.multiline` config
option.

This does not alter the default behavior, multiline support is opt-in.

- Add optional multiline config param
- Add tests to cover multiline support
- Fix some clippy lints

Fixes #26.

Signed-off-by: Joe Grund <jgrund@whamcloud.io>

2022-03-16 15:47 UTC, QEDK commented
> This patch adds optional multiline support with the `Ini.multiline` config option.
> 
> This does not alter the default behavior, multiline support is opt-in.
> 
>     * Add optional multiline config param
> 
>     * Add tests to cover multiline support
> 
>     * Fix some clippy lints
> 
> 
> Fixes #26.
> 
> Signed-off-by: Joe Grund [jgrund@whamcloud.io](mailto:jgrund@whamcloud.io)

Appreciate the PR, will review soon. 🙌

2022-03-23 20:03 UTC, jgrund commented
Hi, any updates?

2022-04-20 20:13 UTC, QEDK requested changes

2022-04-20 20:13 UTC, QEDK commented on src/ini.rs
> +                            "line {} started with identation but there is no current entry",
typo: `indentation`

2022-04-20 20:13 UTC, QEDK commented on src/ini.rs
> +            let line = match line.find(|c: char| self.comment_symbols.contains(&c)) {
Please don't reuse/shadow variable names. It's an intentional design decision.

2022-08-06 21:51 UTC, VirxEC commented
@jgrund please fix these minor problems, multiline support would be very nice :pray:

2022-08-28 16:11 UTC, QEDK commented
Close in favour of #31

2022-08-28 16:11 UTC, closed without merging